const ORDER = { critical: 0, high: 1, medium: 2, low: 3 };
const esc = (s) =>
  String(s ?? "").replace(/[&<>"]/g, (c) => ({ "&": "&amp;", "<": "&lt;", ">": "&gt;", '"': "&quot;" })[c]);

export function sortFindings(findings) {
  return [...findings].sort((a, b) => (ORDER[a.severity] ?? 9) - (ORDER[b.severity] ?? 9));
}

export function counts(findings) {
  const c = { critical: 0, high: 0, medium: 0, low: 0 };
  for (const f of findings) if (f.severity in c) c[f.severity]++;
  return c;
}

export function toMarkdown({ repo, findings, survey, runId, status }) {
  const sorted = sortFindings(findings);
  const c = counts(sorted);
  const lines = [
    `# Audit — ${repo}`,
    "",
    `${survey.files} files scanned · ${sorted.length} findings ` +
      `(critical ${c.critical} · high ${c.high} · medium ${c.medium} · low ${c.low})`,
    "",
    `<sub>run \`${runId}\` · ${status} · generated by fable-audit on oh-my-fable</sub>`,
    "",
  ];
  if (!sorted.length) lines.push("No findings recorded.", "");
  for (const f of sorted) {
    const where = f.file ? ` — \`${f.file}${f.line ? `:${f.line}` : ""}\`` : "";
    lines.push(
      `## [${f.severity}] ${f.title}`,
      "",
      `**${f.category}**${where}`,
      "",
      `**What's there.** ${f.evidence}`,
      "",
      `**Why it matters.** ${f.impact}`,
      "",
      `**Fix.** ${f.fix}`,
      "",
    );
  }
  return lines.join("\n");
}

export function toHtml({ repo, findings, survey, runId, status }) {
  const sorted = sortFindings(findings);
  const c = counts(sorted);
  const tile = (label, n, key) =>
    `<div class="tile ${key}"><span class="n">${n}</span><span class="l">${label}</span></div>`;

  const cards = sorted.length
    ? sorted
        .map(
          (f) => `<article class="f ${esc(f.severity)}">
  <header>
    <span class="sev">${esc(f.severity)}</span>
    <h2>${esc(f.title)}</h2>
  </header>
  <p class="meta">${esc(f.category)}${f.file ? ` · <code>${esc(f.file)}${f.line ? `:${esc(f.line)}` : ""}</code>` : ""}</p>
  <dl>
    <dt>What's there</dt><dd>${esc(f.evidence)}</dd>
    <dt>Why it matters</dt><dd>${esc(f.impact)}</dd>
    <dt>Fix</dt><dd>${esc(f.fix)}</dd>
  </dl>
</article>`,
        )
        .join("\n")
    : `<p class="empty">No findings were recorded for this run.</p>`;

  return `<title>Audit — ${esc(repo)}</title>
<style>
  :root {
    --bg: #fbfbfa; --panel: #fff; --ink: #1a1a19; --dim: #6b6b66; --line: #e4e4e0;
    --critical: #b4232c; --high: #c2610a; --medium: #8a7000; --low: #4a6b7c; --accent: #2d5f4c;
  }
  :root:not([data-theme="light"]) { }
  @media (prefers-color-scheme: dark) {
    :root:not([data-theme="light"]) {
      --bg: #161715; --panel: #1e1f1d; --ink: #eceae4; --dim: #9a9a92; --line: #303130;
      --critical: #f2666e; --high: #f0a04b; --medium: #d9bf4a; --low: #8fb6c9; --accent: #7fc4a4;
    }
  }
  :root[data-theme="dark"] {
    --bg: #161715; --panel: #1e1f1d; --ink: #eceae4; --dim: #9a9a92; --line: #303130;
    --critical: #f2666e; --high: #f0a04b; --medium: #d9bf4a; --low: #8fb6c9; --accent: #7fc4a4;
  }
  * { box-sizing: border-box; }
  body {
    margin: 0; padding: 3rem 1.25rem 6rem; background: var(--bg); color: var(--ink);
    font: 16px/1.6 ui-sans-serif, -apple-system, "Segoe UI", system-ui, sans-serif;
  }
  .wrap { max-width: 52rem; margin: 0 auto; }
  h1 { font-size: 1.9rem; margin: 0 0 .35rem; letter-spacing: -.02em; }
  .sub { color: var(--dim); margin: 0 0 2rem; font-size: .9rem; }
  .tiles { display: flex; flex-wrap: wrap; gap: .6rem; margin-bottom: 2.5rem; }
  .tile {
    flex: 1 1 6rem; background: var(--panel); border: 1px solid var(--line);
    border-radius: 10px; padding: .8rem .9rem; display: flex; flex-direction: column;
  }
  .tile .n { font-size: 1.6rem; font-weight: 650; line-height: 1.1; font-variant-numeric: tabular-nums; }
  .tile .l { color: var(--dim); font-size: .75rem; text-transform: uppercase; letter-spacing: .06em; }
  .tile.critical .n { color: var(--critical); } .tile.high .n { color: var(--high); }
  .tile.medium .n { color: var(--medium); } .tile.low .n { color: var(--low); }
  .f {
    background: var(--panel); border: 1px solid var(--line); border-left: 3px solid var(--line);
    border-radius: 10px; padding: 1.1rem 1.25rem; margin-bottom: 1rem;
  }
  .f.critical { border-left-color: var(--critical); } .f.high { border-left-color: var(--high); }
  .f.medium { border-left-color: var(--medium); } .f.low { border-left-color: var(--low); }
  .f header { display: flex; align-items: baseline; gap: .6rem; }
  .f h2 { font-size: 1.05rem; margin: 0; letter-spacing: -.01em; }
  .sev {
    font-size: .68rem; text-transform: uppercase; letter-spacing: .07em; font-weight: 650;
    padding: .12rem .45rem; border-radius: 4px; border: 1px solid currentColor; flex: none;
  }
  .critical .sev { color: var(--critical); } .high .sev { color: var(--high); }
  .medium .sev { color: var(--medium); } .low .sev { color: var(--low); }
  .meta { color: var(--dim); font-size: .82rem; margin: .4rem 0 .9rem; }
  code { font: .85em ui-monospace, SFMono-Regular, Menlo, monospace; overflow-wrap: anywhere; }
  dl { margin: 0; display: grid; grid-template-columns: minmax(0,1fr); gap: .15rem; }
  dt {
    font-size: .72rem; text-transform: uppercase; letter-spacing: .06em;
    color: var(--dim); margin-top: .7rem;
  }
  dd { margin: 0; }
  .empty { color: var(--dim); }
  footer { margin-top: 3rem; padding-top: 1.2rem; border-top: 1px solid var(--line); color: var(--dim); font-size: .82rem; }
  footer a { color: var(--accent); }
</style>
<div class="wrap">
  <h1>Audit — ${esc(repo)}</h1>
  <p class="sub">${survey.files} files scanned · run <code>${esc(runId)}</code> · ${esc(status)}</p>
  <div class="tiles">
    ${tile("critical", c.critical, "critical")}
    ${tile("high", c.high, "high")}
    ${tile("medium", c.medium, "medium")}
    ${tile("low", c.low, "low")}
  </div>
  ${cards}
  <footer>
    Generated by <strong>fable-audit</strong>, running on
    <a href="https://www.npmjs.com/package/oh-my-fable">oh-my-fable</a> —
    a durable agent harness, so this audit survives a crash and resumes where it stopped.
  </footer>
</div>
`;
}
